{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
    {{ if eq .Values.serviceAccount.provider "aws" }}
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.arn }}"
    {{ else if eq .Values.serviceAccount.provider "gcp" }}
    iam.gke.io/gcp-service-account: "{{ .Values.serviceAccount.name }}@{{ .Values.serviceAccount.project_id }}.iam.gserviceaccount.com"
    {{ end }}
{{- end }}
