# Nginx ingress
namespace:
  name: "ingress-nginx"

provider: "gcp"
aws:
  awsDomainCert: "arn"
  vpcCIDR: ""

nginx:
  version: 1.9.6
  ingress_nginx_controller_image: registry.k8s.io/ingress-nginx/controller:v1.9.6@sha256:1405cc613bd95b2c6edd8b2a152510ae91c7e62aea4698500d23b2145960ab9c
  kube_webhook_certgen_image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20231226-1a7112e06@sha256:25d6a5f11211cc5c3f9f2bf552b585374af287b4debf693cacbe2da47daa5084

# If the domain has a A lets Encrypt Certificate supply it here
tlsSecret:
  enabled: false
  default_ssl_certificate: false
  keyPath: ""
  crtPath: ""

# Deploy tes page
#   Will return SUCCESS on https://ingress-test.{{ .Values.domainName }}
ingressTest:
  enabled: true
  domain: "site.cloud.k2view.com"

# CUSTOM ERROR Custome error page
# Following is a flip switch to enable Custom Error pages in the Ingress Nginx Controller
errorPage:
  enabled: true
  domain: "site.cloud.k2view.com"

  image: "docker.share.cloud.k2view.com/k2view/error-page:latest"
 
  # The redirect to link to be set in the custom error
  secrets:
    K2_MANAGER_URL: "https://cloud.k2view.com"

  resource_allocation:
    requests:
      memory: 128Mi
      cpu: '0.1'
    limits:
      memory: 256Mi
      cpu: '0.4'
