{{- if .Values.errorPage.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-errors
  namespace: {{ .Values.namespace.name }}
  labels: &id001
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-errors
      app.kubernetes.io/part-of: {{ .Values.namespace.name }}
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - imagePullPolicy: IfNotPresent
        image: {{ .Values.errorPage.image }}
        name: nginx-errors-page
        env:
          - name: K2_MANAGER_URL
            value: {{ .Values.errorPage.secrets.K2_MANAGER_URL }}
        ports:
        -  containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: {{ .Values.errorPage.resource_allocation.limits.memory }}
            cpu: {{ .Values.errorPage.resource_allocation.limits.cpu }}
          requests:
            memory: {{ .Values.errorPage.resource_allocation.requests.memory }}
            cpu: {{ .Values.errorPage.resource_allocation.requests.cpu }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-errors
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: {{ .Values.namespace.name }}
spec:
  selector:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: {{ .Values.namespace.name }}
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-errors-ingress
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - "*.{{ .Values.errorPage.domain }}"
  rules:
  - host: "*.{{ .Values.errorPage.domain }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-errors
            port:
              number: 80
{{- end }}