{{- if .Values.errorPage.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: 404-config-secrets
  namespace: {{ .Values.namespace.name }}
data:
  K2_MANAGER_URL: {{ .Values.errorPage.secrets.K2_MANAGER_URL | default "''" | b64enc }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-errors
  namespace: {{ .Values.namespace.name }}
  labels: &id001
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-errors
      app.kubernetes.io/part-of: {{ .Values.namespace.name }}
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - imagePullPolicy: IfNotPresent
        image: {{ .Values.errorPage.image }}
        name: dev-404
        env:
          - name: K2_MANAGER_URL
            valueFrom:
              secretKeyRef:
                name: 404-config-secrets
                key: K2_MANAGER_URL
        ports:
        -  containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: {{ .Values.errorPage.resource_allocation.limits.memory }}
            cpu: {{ .Values.errorPage.resource_allocation.limits.cpu }}
          requests:
            memory: {{ .Values.errorPage.resource_allocation.requests.memory }}
            cpu: {{ .Values.errorPage.resource_allocation.requests.cpu }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-errors
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: {{ .Values.namespace.name }}
spec:
  selector:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: {{ .Values.namespace.name }}
  ports:
    - port: 80
---
{{- if .Values.tlsSecret.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: wildcard-certificate-test
  namespace: {{ .Values.namespace.name }}
data:
  tls.key: "{{- .Files.Get .Values.tlsSecret.keyPath | b64enc }}"
  tls.crt: "{{- .Files.Get .Values.tlsSecret.crtPath | b64enc }}"
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-errors-ingress
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  {{- if .Values.tlsSecret.enabled }}
  tls:
  - hosts:
    - "*.{{ .Values.errorPage.domain }}"
    secretName: wildcard-certificate-test
  {{- end }}
  rules:
  - host: "*.{{ .Values.errorPage.domain }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-errors
            port:
              number: 80
{{- end }}