{{- if .Values.ingressTest.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-test
  labels:
    app.kubernetes.io/name: ingress-test
---    
kind: Pod
apiVersion: v1
metadata:
  name: ingress-test-app
  namespace: ingress-test
  labels:
    app: ingress-test
spec:
  containers:
    - name: ingress-test-app
      image: hashicorp/http-echo
      args:
        - "-text=SUCCESS"
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-test-service
  namespace: ingress-test
spec:
  selector:
    app: ingress-test
  ports:
    - port: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test
  namespace: ingress-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - ingress-test.{{ .Values.ingressTest.domain }}
  rules:
  - host: ingress-test.{{ .Values.ingressTest.domain }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ingress-test-service
              port:
                number: 5678
{{- end }}