{{- if .Values.tlsSecret.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: wildcard-certificate
  namespace: {{ .Values.namespace.name }}
data:
  tls.key: "{{- .Files.Get .Values.tlsSecret.keyPath | b64enc }}"
  tls.crt: "{{- .Files.Get .Values.tlsSecret.crtPath | b64enc }}"
{{- end }}