# Default values for k2-default.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



global:
  # AWS VPC cidr containing the K8s cluster
  vpcCIDR: 10.0.0.0/16
    # required: true

  # Kubernetes Cluster Name
  clusterName: null
    # required: true

# Chart: charts/gcp-monitoring-collectors
# Manifest specific values: 02-opreator.yaml
gcp-monitoring-collectors:

  # GCP params
  projectId: k2view-rnd
  location: me-west1

  operator:
    image: "gke.gcr.io/prometheus-engine/operator:v0.5.0-gke.0"

# Chart: charts/nginx-ingress
# Manifest specific values: ingress-controller.yaml
nginx-ingress:

  # to be associated with ingress-controller Route53 domain certificate
  awsDomainCert: arn:aws:acm:aws-region:account-id:certificate/arn
    # required: true
  
  # Top domain the would accomidate sub domains
  domainName: "eu-central-2-aws.cloud-dev.k2view.com"
    # required: true

karpenter:

  # ARN of IAM Role (Instance Porfile) that allows Sts assume role to Karpenter Role - Refer to doc...
  instanceProfileARN: ""

  # Karpenter Dependancy chart values
  karpenter:
    enabled: true
    settings:
      aws:
        clusterName: ""
        defaultInstanceProfile: KarpenterNodeInstanceProfile-${CLUSTER_NAME}
        interruptionQueueName: ${CLUSTER_NAME}
    controller:
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi