apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app_name }}
    {{- range $label := .Values.labels }}
    {{ $label.name }}: {{ $label.value }}
    {{- end }}
spec:
  type: 
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: {{ .Values.app_name }}-port
  selector:
    app: {{ .Values.app_name }}