# Default values for K2view agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  create: true
  name: "k2view-agent"

image:
  url: "docker.share.cloud.k2view.com/k2view/k2v-agent:latest"

  repoSecret:
    name: "registry-secret"
    enabled: false
    dockerRegistry:
      auths:
        "docker.share.cloud.k2view.com":
          username: ""
          password: ""

# Secrets used to config the agent
secrets:
  K2_MAILBOX_ID: ""
  K2_MANAGER_URL: "https://cloud.k2view.com/api/mailbox"
  kubeInterface: "https://kubernetes.default.svc"
  #kubeToken: ""
  CLOUD: "" # GCP|AWS
  REGION: ""
  SPACE_SA_ARN: "" # AWS SA only 
  PROJECT: ""

secrets_from_file:
  TLS_KEY_PATH: "secrets/key.pem"
  TLS_CERT_PATH: "secrets/cert.pem"

resources:
  requests:
    memory: 128Mi
    cpu: '0.1'
  limits:
    memory: 256Mi
    cpu: '0.4'

serviceAccount:
  # will create service account with cluster role and secret with tocken of this SA
  create: true
  provider: ""   #aws|gcp
  arn: ""        # For AWS role
  gcp_service_account_name: "" # For GCP sa
  project_id: "" # For GCP SA

  # Role for SA
  role:
    rules:
      - apiGroups: [""]
        resources: ["namespaces"]
        verbs: ["create", "delete", "get"]
      - apiGroups: ["apps"]
        resources: ["deployments", "statefulsets"]
        verbs: ["create", "delete", "list", "get", "patch"]
      - apiGroups: ["batch"]
        resources: ["jobs", "jobs/status"]
        verbs: ["create", "delete", "get", "list"]
      - apiGroups: ["networking.k8s.io"]
        resources: ["ingresses", "networkpolicies"]
        verbs: ["create", "delete","get"]
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["delete", "list"]
      - apiGroups: [""]
        resources: ["configmaps", "secrets"]
        verbs: ["create", "delete", "list", "patch","get"]
      - apiGroups: [""]
        resources: ["services", "persistentvolumeclaims"]
        verbs: ["create", "delete", "get", "list"]
      - apiGroups: ["monitoring.coreos.com"]
        resources: ["podmonitors"]
        verbs: ["create", "delete"]
      - apiGroups: [""]
        resources: ["serviceaccounts"]
        verbs: ["create", "delete", "get", "list", "patch"]

